### ISSUE TITLE
Whether SWD support is available? (EUB-55)

### ISSUE THREAD

**Issue by Yecgaa1** [espressif/esp-usb-bridge#16]
Some development boards only lead to the SWD interface without Jtag interface, may I ask whether SWD is supported in this project at present or whether there is any plan to support it in the future
Thanks

**Comment by DNedic** [comment]
Hello @Yecgaa1 , currently we don't support SWD. Whether we will support it in the future is not certain yet, but we will keep this in mind as a feature request.

**Comment by dobairoland** [comment]
Solved by 40bd6ed1d0ac79312a2b960d3bb4403c8a329380
