### ISSUE TITLE
download failed under Windows (EUB-60)

### ISSUE THREAD

**Issue by wuxx** [espressif/esp-usb-bridge#19]
Hello, in the past, I have been using esp-usb-bridge under Linux without any issues. Just now I found that it cannot be downloaded smoothly on Windows. It seems that there are some bugs in the source code, possibly related to the collaboration with esptool.py. I compiled the latest code, but the same problem persists. The specific situation is as follows:

![image](https://github.com/espressif/esp-usb-bridge/assets/1648489/96d4b9d4-7b4c-4eb0-884b-d5736acb2c31)

The issue seems to occur during the change of the baudrate. If I use the -b 115200 parameter (i.e.,  do not need to change the baudrate), then the programming is successful."

**Comment by wuxx** [comment]
Programming with the "-b 115200" parameter is successful.

![image](https://github.com/espressif/esp-usb-bridge/assets/1648489/83dfc2b6-21e9-4a06-8437-d39146cbbf3c)

**Comment by wuxx** [comment]
I just checked the waveform file and source code. The reason is that this function call did not switch the baud rate correctly.

![image](https://github.com/espressif/esp-usb-bridge/assets/1648489/ea6c2e14-d293-4df1-b30f-8fb52e845b4b)

**Comment by DNedic** [comment]
@wuxx Thank you for your report, can you try UF2 flashing with the bridge, and using `esptool` with an USB to serial converter. That would help us better pinpoint the issue, and if indeed this seems to be an `esptool` issue, please submit an issue in the `esptool` repository.

**Comment by DNedic** [comment]
Thanks, so there might indeed be an issue in the interaction of `esptool` and `esp-usb-bridge`, I will try reproducing the issue.

**Comment by wuxx** [comment]
Okay, I just opened an issue under esptool repo
https://github.com/espressif/esptool/issues/939

**Comment by DNedic** [comment]
I have managed to reproduce and diagnose the issue, a fix is on the way.

**Comment by wuxx** [comment]
Hi, DNedic, I checked the submitted code, but I still don’t quite understand why it can work normally on Linux but not on Windows,  Can you explain it briefly?

**Comment by DNedic** [comment]
> Hi, DNedic, I checked the submitted code, but I still don’t quite understand why it can work normally on Linux but not on Windows, Can you explain it briefly?

Hello @wuxx , the reason is that the windows virtual com port driver keeps sending DTR = 0, RTS = 0 during flashing. Because the `tud_cdc_line_state_cb()` called `serial_set_baudrate()` when DTR and RTS are not both asserted, under an assumption that this will only happen when resetting the device, this causes the baudrate to be erratically changed during flashing. 
 
Now we are checking whether RTS is asserted (translating to reset) and only change the baudrate to default when the device is reset.
