### ISSUE TITLE
Mass Storage Device, ESP LOADER connection failed! (EUB-61)

### ISSUE THREAD

**Issue by seulater** [espressif/esp-usb-bridge#20]
ESP32-S3-DevKitC-1 v1.6, IDF v5.1.2. Using VSC on PC. 

Compiled fine, uploaded and runs.  New drive " ESPPROG_MSC " appears in my computer. 
Did the " idf.py uf2 " and when I drag and drop the uf2.bin file to the new drive, i get the following error in the terminal. 

> I (923910) bridge_msc: LBA 691: UF2 block 0 of 47 for chip ESP32-S3 at 00000000 with length 452
> E (925860) bridge_msc: ESP LOADER connection failed!
> I (925860) bridge_msc: LBA 691: UF2 block 0 of 47 for chip ESP32-S3 at 00000000 with length 452
> E (927810) bridge_msc: ESP LOADER connection failed!
> I (927810) bridge_msc: LBA 691: UF2 block 0 of 47 for chip ESP32-S3 at 00000000 with length 452
> E (929760) bridge_msc: ESP LOADER connection failed!
> I (929760) bridge_msc: LBA 691: UF2 block 0 of 47 for chip ESP32-S3 at 00000000 with length 452
> E (931710) bridge_msc: ESP LOADER connection failed!
> I (931710) bridge_msc: LBA 691: UF2 block 0 of 47 for chip ESP32-S3 at 00000000 with length 452
> E (933660) bridge_msc: ESP LOADER connection failed!
> I (933660) bridge_msc: LBA 691: UF2 block 0 of 47 for chip ESP32-S3 at 00000000 with length 452
> E (935610) bridge_msc: ESP LOADER connection failed!
> I (935610) bridge_msc: LBA 691: UF2 block 0 of 47 for chip ESP32-S3 at 00000000 with length 452
> E (937560) bridge_msc: ESP LOADER connection failed!
> I (937560) bridge_msc: LBA 691: UF2 block 0 of 47 for chip ESP32-S3 at 00000000 with length 452
> E (939510) bridge_msc: ESP LOADER connection failed!
> I (939510) bridge_msc: LBA 691: UF2 block 0 of 47 for chip ESP32-S3 at 00000000 with length 452
> E (941460) bridge_msc: ESP LOADER connection failed!
> I (941460) bridge_msc: LBA 691: UF2 block 0 of 47 for chip ESP32-S3 at 00000000 with length 452
> E (943410) bridge_msc: ESP LOADER connection failed!
> I (943410) bridge_msc: LBA 691: UF2 block 0 of 47 for chip ESP32-S3 at 00000000 with length 452
> E (945360) bridge_msc: ESP LOADER connection failed! 

Any ideas why ?

**Comment by dobairoland** [comment]
@seulater So this is no longer an issue and can be closed?
