### ISSUE TITLE
Any way to flash new software without BOOT button? (EUB-69)

### ISSUE THREAD

**Issue by mickeyl** [espressif/esp-usb-bridge#23]
I have been delievered two esp-usb-bridge hardware devices, one has a broken BOOT button. Is there a way to flash new software to that hardware without the BOOT button being pressable?

**Comment by dobairoland** [comment]
Can you please be more specific about the hardware device? I don't think we sell anything right now with esp-usb-bridge but I know about some non-Espressif board manufacturers who sell devices with esp-usb-bridge (usually they have their own issue trackers).

Generally speaking, If the serial RTS & DTR signals are connected to the Reset and Boot pins of an ESP32(-*) device then the device can be flashed with esptool without pressing the Boot button. More about this can be found at https://docs.espressif.com/projects/esptool/en/latest/esp32/advanced-topics/boot-mode-selection.html#automatic-bootloader.

**Comment by mickeyl** [comment]
https://docs.espressif.com/projects/esp-dev-kits/en/latest/esp32s3/esp32-s3-usb-bridge/index.html ­– isn't this an official Espressif device?
![image](https://github.com/espressif/esp-usb-bridge/assets/167469/09006e79-a038-4377-8373-27495a11edf6)

 As far as I understand the schematics, RTS & DTR for the S3 are not available through the pin headers…

**Comment by dobairoland** [comment]
Yes, I'm sorry, I forgot about that one. It was done by a completely different team.

If I read [this table](https://docs.espressif.com/projects/esp-dev-kits/en/latest/esp32s3/esp32-s3-usb-bridge/user_guide.html#gpio-allocation) well then pin no. 3 is the boot signal for the module. Have you tried to connect it to GND while powering it up (sticking it into the USB slot)?

**Comment by DNedic** [comment]
Perhaps it would be best to try [DFU](https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-guides/dfu.html) or [esp-usb-jtag](https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-guides/jtag-debugging/index.html#upload-application-for-debugging)?

**Comment by mickeyl** [comment]
Shortening the boot pin and the ground has no effect on this device.

I might try JTAG.

**Comment by mickeyl** [comment]
FWIW, it looks like the latest software/documentation for this device is here: https://github.com/espressif/esp-dev-kits/tree/master/esp32-s3-usb-bridge/examples/usb_wireless_bridge/

**Comment by dobairoland** [comment]
I'm closing this because this is not a firmware issue. I can recommend to send back the damaged board if you are not able to use the above recommendations.
